# Default site wide settings
[build.processing]
  skip_processing = true

# Branch specific settings
[context.main.processing]
  skip_processing = false
[context.main.processing.css]
  bundle = true
  minify = true